### ISSUE TITLE
RE: Posting error

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1851] opened 2024-11-08 05:19 UTC

**Comment by Prakash3K** [comment] 2024-11-14 11:09
Waiting for Kumar G sir confirmation to close this ticket

CC: @audhi3k @Tushargupta3K @TabrejAlam3K

**Comment by Tushargupta3K** [comment] 2024-11-20 07:30
This issue happened due to bulk upload posting at another user session.
Since bulk upload shifted to night it must not arise again.

**Comment by Prakash3K** [comment] 2024-11-20 12:05
Client confirmed to close this ticket 


CC: @audhi3k @TabrejAlam3K

**Closed as completed by Prakash3K** 2024-11-20 12:05 UTC
