### ISSUE TITLE
E-invoice for Export - validation error 

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#776] opened 2023-09-12 07:54 UTC

**Comment by Jayanth3KT** [comment] 2023-09-12 07:59
Dear 3KT Team,

We are unable to upload the JSON file generated for an export invoice 33-23-1232 due to validation error.

“The field shipping Bill No must a string with a minimum length of 1 and a maximum length of 20”

JSON and validation error pdf are attached for your investigation and providing a solution at the earliest.

Attached documents 

[EXPORT-ERROR-EINV PORTAL.pdf](https://github.com/3ktech/General/files/12583830/EXPORT-ERROR-EINV.PORTAL.pdf)

(There is one more attachment called json file couldn't upload it here )

**Comment by Amar-3KT** [comment] 2023-09-14 03:42
@3ktech -any technical available for this ticket

**Comment by Mahesh3ktech** [comment] 2023-09-14 05:48
hi @Amar-3KT - yesterday evening i have connected with Jayanth to discuss about task but he is not having sufficient information. Can we connect today to discuss requirement.

CC: @3ktech

**Comment by Ejaz3KT** [comment] 2023-09-24 13:27
Hi @Mahesh3ktech The Fitchner users are not able to upload the JSON file in the GST portal they are facing a Validation error for your reference I`ve attached the screen below

![Image](https://github.com/3ktech/General/assets/125632927/8a832355-04c5-4b99-a8f6-5e3ecc08f8ab)

CC: @audhi3k  @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-09-26 12:25
I`ve explain the issue to Mr. Mahesh he started working on it

CC: @Mahesh3ktech @Amar-3KT @audhi3k

**Comment by Ejaz3KT** [comment] 2023-09-27 11:29
Hi @Mahesh3ktech Can you please update the status of this task

CC: @audhi3k @Amar-3KT

**Comment by Mahesh3ktech** [comment] 2023-09-27 11:48
hi @Ejaz3KT - I have analyzed the issue, issue is due to field value coming blank so when client generate json then while uploading getting error due validation. when we discussed with client, they informed that for service, shipping bill no. will not be there so always it comes blank. so, we suggested to add at least zero to that field. but client asked us to do hardcode and update value for that we need to extend the standard action code. currently I'm doing changes. 

CC: @3ktech, @audhi3k

**Comment by Ejaz3KT** [comment] 2023-09-27 11:49
Thank you Mr. @Mahesh3ktech

**Comment by Ejaz3KT** [comment] 2023-09-28 04:00
We  have shown the changes that we have made to the Sales invoice JSN file Mr. Murali told us he need to get confirmation about the changes from their authority

**Comment by Ejaz3KT** [comment] 2023-09-29 11:31
Waiting for the client confirmation

CC: @Mahesh3ktech @audhi3k

**Comment by Ejaz3KT** [comment] 2023-10-09 04:41
I`ve mailed them to give us confirmation regarding this E-invoice issue let see when they we send us confirmation mail (Still waiting for the client confirmation)

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-10-16 04:12
Waiting for the Client's approval

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-10-16 10:40
Hi @Mahesh3ktech Client has confirmed regarding system modification date now we can proceed with our work on this task.

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-10-19 04:42
Hi @Mahesh3ktech Please update the status of this task I hope it has been fixed now

CC: @Amar-3KT @audhi3k

**Comment by Ejaz3KT** [comment] 2023-10-19 09:01
Hi @Mahesh3ktech We have tested it in UAT sandbox it is fine please deploy the same in production 

CC: @audhi3k @gsudarsan3k

**Comment by Ejaz3KT** [comment] 2023-10-19 12:06
Hi @gsudarsan3k  Is the changes has deployed in the production?

CC: @audhi3k @Amar-3KT @Mahesh3ktech

**Comment by Ejaz3KT** [comment] 2023-10-20 07:03
Hi @Mahesh3ktech It is deploy in the production?

**Comment by Mahesh3ktech** [comment] 2023-10-20 08:13
hi @Ejaz3KT - yes deployment is done in production.

**Comment by Ejaz3KT** [comment] 2023-10-20 08:40
Ok Mr. @Mahesh3ktech Thank you

**Comment by Ejaz3KT** [comment] 2023-10-26 05:39
Client mentioned that the they will test the scenario and give us feedback on 30-Oct-2023

CC: @audhi3k

**Comment by Ejaz3KT** [comment] 2023-11-14 11:00
The client has confirmed we can close this ticket

CC: @audhi3k @Mahesh3ktech

**Closed as completed by Ejaz3KT** 2023-11-14 11:00 UTC
