### ISSUE TITLE
Vendor Payment Upload - Excel format

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#815] opened 2023-09-21 12:08 UTC

**Comment by Jayanth3KT** [comment] 2023-09-21 12:08
<html>
<body>
<p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size: 10pt; font-family: &quot;Segoe UI&quot;, sans-serif;">Reference Subject: Vendor Payment Upload</span><br><span style="font-size: 10pt; font-family: &quot;Segoe UI&quot;, sans-serif;">Action: Yes</span><br><span style="font-size: 10pt; font-family: &quot;Segoe UI&quot;, sans-serif;">Due Date: Immediate</span><br><span style="font-size: 10pt; font-family: &quot;Segoe UI&quot;, sans-serif;">*********************</span></p><p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Dear  3KT Team,</p><p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The excel file generated using “Vendor Payment Upload” report as incorrect vendor Bank A/c no. (if the no. begins with 0) and requires the following corrections/modifications:</p><ol start="1" type="a" style="margin-bottom: 0cm; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li><b>In case of Bank account no. beginning with ‘0’, the ‘0’ is truncated. Eg. For CRS312 ∙ SELCO SOLAR LIGHT PRIVATE LIMITED ‘04253050000028’ is printed as ‘04253050000028’</b></li><li>Date format must be dd/mm/yyyy</li><li>Credit Narration should be printed as “FICHTNER_PAYMENT”</li><li>The sequence of fields should be as below</li></ol>

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
-- | -- | -- | -- | -- | -- | -- | -- | --
Payment Method | Posting Date | Vendor | A/c No | IFSC Code | amount without 1000 separator and two decimal places | Credit Narration 1 | Credit Narration 2 | vendor email

<p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I have enclosed the standard bank upload file which is practise in Fichtner and the report generated via “Vendor payment upload”.</p>
</body>
</html>



[Vendor Payment Upload (1).xlsx](https://github.com/3ktech/General/files/12684270/Vendor.Payment.Upload.1.xlsx)
[Standar Bank upload File - FI.xlsx](https://github.com/3ktech/General/files/12684271/Standar.Bank.upload.File.-.FI.xlsx)

**Comment by gsudarsan3k** [comment] 2023-09-25 04:20
Hi, @Ejaz3KT could you please get the requirement from the client to work on this ticket if development is required?

CC: @audhi3k @3ktech

**Comment by sandhya3k** [comment] 2023-09-26 08:34
@Ejaz3KT 

once u get the all the details please update

**Comment by Ejaz3KT** [comment] 2023-09-26 12:37
Client requires whatever fields are available in their standard  format they need same fields to be printed in this report and remove the old fields

CC: @audhi3k @Amar-3KT @sandhya3k

**Comment by Ejaz3KT** [comment] 2023-09-26 14:10
Hi @sandhya3k Madam Please find the field mapping for the vendor payment upload report.

[Vendor Payment Upload Field Mapping.xlsx](https://github.com/3ktech/General/files/12728582/Vendor.Payment.Upload.Field.Mapping.xlsx)

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-09-27 09:55
Hi @sandhya3k Madam The report is not working fine  data in the fields is not printing please check the report.

![Image](https://github.com/3ktech/General/assets/125632927/f8d1435d-c150-4706-bb8c-cc9e32eeccd3)

![Image](https://github.com/3ktech/General/assets/125632927/703ef894-6e1d-4e12-95a8-fa51eac5d535)

CC: @audhi3k @Amar-3KT

**Comment by sandhya3k** [comment] 2023-09-28 04:00
@Ejaz3KT \

PLEASE test in sandbox?

**Comment by Ejaz3KT** [comment] 2023-09-28 04:05
Ok I`ll test

**Comment by Ejaz3KT** [comment] 2023-09-28 04:21
Hi @sandhya3k Madam I`ve tested the report there is a issue in bank account field it is coping same bank account for other vendors as well

![Image](https://github.com/3ktech/General/assets/125632927/58cbbf0a-fd2a-4031-b96c-47cf47a77bdc)

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-09-28 05:40
Hi @sandhya3k Madam I`ll test the report then I`ll show to the client if any changes required I`ll update you

**Comment by Ejaz3KT** [comment] 2023-09-28 10:24
Hi @sandhya3k Fitchner team asked to add the new field in report Please find the attached new field mapping for that report. The changes which you have to do in the report I`ve mention below:

1. Posting Date should be like 28/09/2023
2. Payment Method should NFT for all Lines  
3. Credit Narration 2 Should be Pay To: (External Doc No.)
4. Our Email Field should be add in the report 

[Vendor Payment Upload Field Mapping.xlsx](https://github.com/3ktech/General/files/12748310/Vendor.Payment.Upload.Field.Mapping.xlsx)

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-10-03 05:33
Hi @sandhya3k Madam can you please update the status of this report 

CC: @audhi3k

**Comment by sandhya3k** [comment] 2023-10-03 05:55
@Ejaz3KT 
please test?

cc : @audhi3k

**Comment by Ejaz3KT** [comment] 2023-10-03 08:17
Ok @sandhya3k Madam I`ll test and update

**Comment by Ejaz3KT** [comment] 2023-10-03 11:19
Hi @sandhya3k Madam I`ve tested the report some of the fields are not fetching the date like
1. Vendor Account No Is coming blank in the RDL report
2. The amount should not be negative in the excel report

![Image](https://github.com/3ktech/General/assets/125632927/3a4eb960-f812-4371-a0f3-83fa6c4eafb7)

![Image](https://github.com/3ktech/General/assets/125632927/8921e3d3-f6c8-4a6c-be29-33e33231be04)

CC: @Amar-3KT @audhi3k

**Comment by Ejaz3KT** [comment] 2023-10-04 12:53
Due to client unavailability, I`ve done the UAT today

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-10-05 12:16
Mr. Murali told me he would connect after lunch for the UAT session but due to time posting work he is not connected 

CC: @Amar-3KT @audhi3k

**Comment by Ejaz3KT** [comment] 2023-10-06 06:23
I am trying to connect with Mr. Murali for the UAT session he is not available at this moment

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-10-09 04:37
Mr. Murali sir said he will connect in the second half for the UAT session

CC: @audhi3k

**Comment by Ejaz3KT** [comment] 2023-10-09 13:41
Today  Mr. Murali has not connected with me for the UAT session due to his busy schedule 

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-10-10 06:25
UAT session has been done with Mr. Murali he will check at their end and give us confirmation

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-10-16 04:11
Waiting for the Client's confirmation

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-10-16 09:21
Hi @sandhya3k  I had a call with Mr. Murali he told me to deploy this report in the production I am requesting you to Please deploy this purchase register report in the Fitchner production environment.

CC: @audhi3k @Amar-3KT

**Comment by Ejaz3KT** [comment] 2023-10-17 11:46
Due to Ms. @sandhya3k Madam being on leave to so deployment has not been done  today

CC: @audhi3k

**Comment by Ejaz3KT** [comment] 2023-10-19 12:07
Hi @gsudarsan3k  Is the changes has deployed in the production?

CC: @audhi3k @Amar-3KT @sandhya3k

**Comment by Ejaz3KT** [comment] 2023-10-20 05:15
The deployment has done in production waiting for the client confirmation

CC: @audhi3k

**Comment by Ejaz3KT** [comment] 2023-10-26 05:36
Client has confirmed we can close this ticket

CC: @audhi3k

**Comment by Jayanth3KT** [comment] 2023-10-26 05:39
Hi @Ejaz3KT can i know total effort hours for this ticket.

**Comment by Ejaz3KT** [comment] 2023-10-26 05:41
HI @Jayanth3KT we have consumed 6 hours for the development

**Closed as completed** 2023-10-26 12:06 UTC
