### ISSUE TITLE
Write offs requested by user but the request didn’t reach to accounts.

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#304] opened 2023-04-21 03:57 UTC

**Comment by Shasthara** [comment] 2023-04-21 04:41
Need to replicate, Vivek will coordinate with user so that it can be replicated

**Comment by 3ktech** [comment] 2023-04-24 06:13
Need to create proper Journal Template and Batch names to make this working @TabrejAlam3K

**Comment by TabrejAlam3K** [comment] 2023-04-24 09:56
Hi Mr. @Shasthara 

Client(Mr. Somendra) will test and confirm the current status.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-04-26 08:38
Mr. Somendra has to confirm.

**Comment by TabrejAlam3K** [comment] 2023-05-09 07:22
Mr. Kartik D said it is working fine.

**Comment by audhi3k** [comment] 2023-05-10 12:03
As per Mr Vivek's mail dated 10thMay2023, the issue is resolved.  Hence closing the case

**Comment by TabrejAlam3K** [comment] 2023-05-15 11:10
We have tested in Production Environment with LKS User (Mr. Vivek and Mr. Somendra) It was working fine.

**Comment by TabrejAlam3K** [comment] 2023-05-19 05:09
@3ktech - The Writeoff request is working fine in LKS Company we need to done the same setup for other two company

1. VLK - V.LAKSHMIKUMARAN
2. VSH - V.SRIDHARAN

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-05-24 06:38
I have done the General Journal Template and Batch setup for Writeoff for below

1. VLK - V.LAKSHMIKUMARAN
2. VSH - V.SRIDHARAN

**Comment by TabrejAlam3K** [comment] 2023-05-25 05:41
Informed to the client to push Writeoff Request against the RTB Which are proceed successfully from BC End.

Company - V.Lakshmikumaran
0000863491
0000863492

Company - V.SRIDHARAN
0000863496
0000863497

**Comment by TabrejAlam3K** [comment] 2023-05-26 03:27
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tabrej\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



Entry No | Rtb No | Invoice No | Payment Date time | Payment Location | Writeoff | Applies-to Doc.   Type | Applies-to Doc.   No. | Applied Amount | Status | API status
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
101 | 863512 | VSH02-2122-00003 | 26-05-2023 08:25 | 1 | Yes | Payment | JVWO/2223/12/0002 | 100 | Approved | Success
100 | 863511 | VSH02-2122-00002 | 26-05-2023 08:25 | 1 | Yes | Payment | JVWO/2223/12/0001 | 100 | Approved | Success
  |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |  
Entry No | Rtb No | Invoice No | Payment Date time | Payment Location | Writeoff | Applies-to Doc. Type | Applies-to Doc. No. | Applied Amount | Status | API status
1 | 863494 | VLK01-2122-00001 | 26-05-2023 08:22 | 1 | Yes | Payment | JVWO/2223/12/0001 | 2031 | Approved | Success



</body>

</html>

**Comment by TabrejAlam3K** [comment] 2023-05-26 05:26
Client (Mr. Vivek) - Confirmation received in UAT it is working fine,

**Comment by TabrejAlam3K** [comment] 2023-05-26 10:08
![Image](https://github.com/3ktech/General/assets/116171982/32cf8e1b-a6b0-4259-83cf-7e8ad7b48423)

**Comment by TabrejAlam3K** [comment] 2023-06-12 05:00
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k

**Closed as completed by TabrejAlam3K** 2023-06-12 05:00 UTC
