### ISSUE TITLE
TDS calculation issue

### ISSUE THREAD

**Issue by Amar-3KT** [3ktech/General#591] opened 2023-07-25 11:33 UTC

**Comment by Amar-3KT** [comment] 2023-07-25 11:39
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | LIVE |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
V1329 | Doc type | doc no | Posting date | Invoice amount | Posted/Pre document | TDS calculating
  | payment | 03-PBP/2023/3811 | 6/13/2023 | 9,16,500.00 | Posted | 0
  | Invoice | 05-PPI/2023/1192 | 7/25/2023 | 1,25,945.00 | Posted | 0
  | Invoice | 05-PI/2023/1890 | 7/25/2023 | 14,02,500.00 | Pre | 1,528.00
  |   |   |   |   |   |  
  | UAT |   |   |   |   |  
V0049 | Doc type | doc no | Posting date | Invoice amount |   | TDS calculating
  | payment | 01-BP/2021/065 | 6/27/2023 | 9,16,500.00 | Posted | 0
  | Invoice | TDSTEST048 | 7/25/2023 | 1,25,945.00 | Posted | 0
  | Invoice | INVOICE-003 | 7/25/2023 | 14,02,500.00 | Pre | 0



</body>

</html>

**Comment by Amar-3KT** [comment] 2023-07-25 11:43
@panduc Kindly check TDS entry on LIVE all code updated correctly or not. on live TDS calculating before 50L limit.

Mentioned scenario working fine in UAT but on LIVE it's not working.

CC @audhi3k

**Comment by Amar-3KT** [comment] 2023-07-26 06:47
@3ktech Any technical available to check code related to TDS.
CC @audhi3k

**Comment by panduc** [comment] 2023-07-28 10:33
@Amar-3KT  As discussed my solution is available in UAT and LIVE DB.

Noticed in LIVE there is some fix 3KTTDSFIX which is not there in UAT DB this code might causing the issue. as I suggested please execute the test cases then we shall identify the issue, check internally who has done  and we will do the proper code cleanup in LIVE.


CC @audhi3k @3ktech

**Comment by Amar-3KT** [comment] 2023-07-28 11:22
We have analyzed that they are picking purchase invoice records through integration due to this TDS nature of deduction not get refresh. We need to remove tds nature of deduction and take it again then it will calculate correctly.(This working for non application)
Same updated to Mr. Suresh and he is checking....

**Comment by Amar-3KT** [comment] 2023-07-31 06:34
In case of application its not working on live. Its happening in case of GST vendor type is unregister, 

when gst vendor type unregister and we are doing application its not checking threshold limit.

**Comment by Amar-3KT** [comment] 2023-07-31 14:42
@panduc Please check is anyone done any changes in code.
Invoice amount is not updating again.

**Comment by Amar-3KT** [comment] 2023-08-01 05:31
Scenario 1

Advance Payment 5L(Posted payment-01-BP/2021/068)
Invoice 6L.00 applied with Avance payment.( Pre document No..... V0051-001 )

TDS calculating on 6L, it should not calculate. (Threshold limit 50L)

Scenario 2

Advance payment 916,500(posted document.....01-BP/2021/067)
Invoice 125,945(posted document ....TDSTEST050)

if invoice amount less then 916500 then not calculating tds, if its more than advance payment its calculating tds.

If amount more than advance amount its calculating TDS, It should not calculate tds(Threshold limit 50L)

**Comment by panduc** [comment] 2023-08-02 04:58
@Amar-3KT the identified new scenario. I've fixed it. did the the unit testing as well.

Please do the functional testing and confirm the same.

**Comment by Amar-3KT** [comment] 2023-08-02 07:20
@panduc  please check document no V0055-001 - For multiple lines. Not calculating tds, 50L crossed for same scenario.

for single line working fine

**Comment by Amar-3KT** [comment] 2023-08-10 05:09
Now Mr. Shiva testing tds issue..

**Comment by panduc** [comment] 2023-08-11 02:01
@Amar-3KT TDS issue i've fixed it and tested. it is working fine.

Please test it and confirm before second off so that we can move it to production.


CC @audhi3k @3ktech

**Comment by panduc** [comment] 2023-08-11 02:47
Object modified details:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/consultant1/AppData/Local/Temp/2/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/consultant1/AppData/Local/Temp/2/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Type | ID | Name | Modified | Version List | Date | Time
-- | -- | -- | -- | -- | -- | --
Table | 25 | Vendor Ledger Entry | Yes | NAVW19.00.00.50785,NAVIN9.00.00.50785,TDS-REGEF-194Q | ######## | 5:07:56 PM
Table | 39 | Purchase Line | Yes | NAVW19.00.00.51014,NAVIN9.00.00.51014,NKG,TDS-REGEF-194Q | ######## | 8:13:03 AM
Codeunit | 90 | Purch.-Post | Yes | NAVW19.00.00.51103,NAVIN9.00.00.51103,TDS-REGEF-194Q | ######## | 5:06:54 PM
Page | 51 | Purchase Invoice | Yes | NAVW19.00.00.51103,NAVIN9.00.00.51103,NKG | ######## | 7:04:49 PM



</body>

</html>

**Comment by panduc** [comment] 2023-08-11 09:19
@Amar-3KT Shiva confirmed to Deploy the latest changes LIVE.

Asked users to logoff. I've checked the action session. Since no active users. I've deployed the changes to NKG production and restarted the services. 

Please communicate the same to Customer.

CC @audhi3k @3ktech

**Comment by panduc** [comment] 2023-08-16 05:21
@shivakumar3k  Handover has been done to @rohit3k.  Please connect with Rohit for the new cases.

CC @audhi3k @3ktech

**Comment by panduc** [comment] 2023-08-23 17:31
All the identified scenarios fixed.

Shiva  tested and confirmed to Move LIVE DB.

Merged the latest changes and deployed to LIVE DB and restarted it's services.

**Comment by shivakumar3k** [comment] 2023-09-13 10:02
Hi @Padma2717 Received customer approval for Live deployment.
So kindly deploy the latest correction which are made in UAT to Live environment.

Note: Please deploy after 7 PM IST.

Regards,
Shiva Kumar N

**Closed as completed** 2023-09-25 05:09 UTC
