### ISSUE TITLE
ECOMM-1492: GenStore | SwiftLink | BC - T |-CAS-01486-T2Q7C9

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#767] opened 2023-09-11 15:00 UTC

**Comment by Jayanth3KT** [comment] 2023-09-11 15:00
Need to implement the Item Level order status of a sales order based on functional analyses

**Comment by Padma2717** [comment] 2023-10-03 14:49
@Jayanth3KT  Duplicate, please ignore

**Comment by Padma2717** [comment] 2023-10-03 15:08
Duplicate of EComm- 1491

**Closed as completed by Padma2717** 2023-10-03 15:08 UTC
