### ISSUE TITLE
Customer name/client name issue

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#322] opened 2023-04-26 04:44 UTC

**Comment by TabrejAlam3K** [comment] 2023-04-26 05:14
Clients Comments

Customer name/client name: Please attached excel statement which provides three type of errors as detailed below:

1. Posted with Incorrect name in Navision BC– 6 clients
2. Missing client names – 43 clients
3. Mismatch in client name in Navision BC – 4 clients

**Comment by TabrejAlam3K** [comment] 2023-04-26 05:30
Hi Mr. @Shasthara - Point No. 2 (Missing client names – 43 clients) - Completed. ( I have already updated the missing client name)

I need help on Point No. 1 and Point No. 3

CC : @audhi3k @narayana3kt

**Comment by TabrejAlam3K** [comment] 2023-04-26 12:57
Hi Ms. @audhi3k Mam,

I have completed Point No. 2 and 3

Point No. 1 is showing error - **Sorry, the current permissions prevented the action. (TableData Sales Invoice Header Modify: Base Application)**

**Comment by TabrejAlam3K** [comment] 2023-04-27 05:37
I need help from technical side currently Ms. audhilakshmi mam suggest Ms. Sandhya. She will discuss once the take will completed whatever task they have.

**Comment by TabrejAlam3K** [comment] 2023-04-28 04:22
@sandhya3k - I have created the excel file with which field we need to update the data in Posted Documents. Please confirm before modifying the value.

[Default26_04_2023_18_16_59.xlsx](https://github.com/3ktech/General/files/11349766/Default26_04_2023_18_16_59.xlsx)

CC : @audhi3k

**Comment by sandhya3k** [comment] 2023-04-28 08:20
@TabrejAlam3K  

based on the requirement i have done one processing report but when iam trying to run this report i got this error

when u free please let me know, we will connect.


![Image](https://user-images.githubusercontent.com/114206737/235094420-9bcc51af-13c4-419d-b461-c924d1d1fccf.png)

cc: @audhi3k

**Comment by narayana3kt** [comment] 2023-04-28 09:00
Hi Tabrej

I want to be part of this testing,

Regards
Narayana AS

**Comment by sandhya3k** [comment] 2023-04-28 09:36
@TabrejAlam3K 
 
I deployed in production please test

cc: @audhi3k @narayana3kt

**Comment by TabrejAlam3K** [comment] 2023-04-28 13:57
Hi Ms. @sandhya3k - All the records get modified accept one record.

LKS03-2324-00033 - this record alone not modified.

![Image](https://user-images.githubusercontent.com/116171982/235167085-c04ec149-1b53-45b3-9e91-730abd036ba0.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-05-19 03:05
Hi Mr. @panduc - We need to check the table called **Common Master List** (50015) where from it is getting updated.

CC : @audhi3k

**Comment by panduc** [comment] 2023-05-22 11:40
Tabrej Explained that from API Trans Log "SyncClient" has to create/Update Customer and it should create Common Master.

Common Master create functionality i've enabled in CU 50013. Deployed in UAT.

@TabrejAlam3K Please check and confirm.

**Comment by panduc** [comment] 2023-05-23 03:44
@TabrejAlam3K  I've Enabled Common master creation for SyncClient and CreateRTB and CancelRTB(it was already there).

deployed the latest changes in UAT. Please check and confirm

**Comment by TabrejAlam3K** [comment] 2023-05-23 09:29
Please move this changes into the Production.

**Comment by panduc** [comment] 2023-05-23 10:05
Deployment has been done to production.

**Comment by TabrejAlam3K** [comment] 2023-05-26 10:08
![Image](https://github.com/3ktech/General/assets/116171982/1e96872d-ef93-4dbf-9270-3fb04297891a)

**Comment by TabrejAlam3K** [comment] 2023-06-12 05:00
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k

**Closed as completed by TabrejAlam3K** 2023-06-12 05:00 UTC
