### ISSUE TITLE
Cheque voiding: Before posting void is possible

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#240] opened 2023-04-06 03:57 UTC

**Comment by TabrejAlam3K** [comment] 2023-04-17 05:13
Hi Mr. @panduc - Please update your comment over their.

**Comment by audhi3k** [comment] 2023-04-26 04:23
Mr @panduc work on this and update the comments

**Comment by TabrejAlam3K** [comment] 2023-04-27 05:32
Hi Mr. @panduc - Please leave your comments here.

**Comment by audhi3k** [comment] 2023-05-09 09:06
Mr @TabrejAlam3K ,  did you checked with LKS team whether they are able to void the posted cheques

**Comment by TabrejAlam3K** [comment] 2023-05-10 04:10
I have reviewed on Check Voided on Posted Documents see the below attached snapshot.

**Financially Voided**
![Image](https://github.com/3ktech/General/assets/116171982/d25fc957-0ea4-45b0-8143-e09820ce4468)

**Comment by TabrejAlam3K** [comment] 2023-05-10 04:49
Update the issue tracker and close it

**Comment by TabrejAlam3K** [comment] 2023-05-19 04:49
Hi Mr. @panduc - Check is not posted but it is still showing as posted in Check Ledger Entries.

Cheque No. - 0954316

Meanwhile @TabrejAlam3K - I will replicate the scenario in other environment and see the functionality of it.

CC : @audhi3k

**Comment by panduc** [comment] 2023-05-23 04:30
@TabrejAlam3K is the scenario created in UAT/Sandbox?

**Comment by TabrejAlam3K** [comment] 2023-05-25 03:10
Hi Ms. @audhi3k - I have created the scenario in UAT let me discuss with you on.

**Comment by TabrejAlam3K** [comment] 2023-05-26 08:53
Hi Ms. @audhi3k Mam - I have replicate the same scenario in Sandbox but here it is working fine.

1. I have created one document(BP/DEL/2223/SEP/0352) and print the check before posting - In check ledger entries the entries is coming **Printed**

**Comment by TabrejAlam3K** [comment] 2023-05-29 04:01
I have informed Mr. Viswanathan sir to check in the production environment and confirm.

CC : @audhi3k @narayana3kt

**Comment by TabrejAlam3K** [comment] 2023-06-12 05:17
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k

**Closed as completed by TabrejAlam3K** 2023-06-12 05:17 UTC
