### ISSUE TITLE
RE: transfer order issue- reg...

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1911] opened 2024-12-03 10:01 UTC
Dear team,

I am facing one issue in transfers order raised from unit1 factory to UCWS VL, the issue its getting automatically posted without pushing to unicommerce…

Kindly check and rectify…

Reference document no: TS2425014280…

**Comment by Tushargupta3K** [comment] 2024-12-03 10:04
connect ed with Venkat on issue, the issue is transfer order posted without creating GRN in UC. RCA - validation depends on subcontracting boolean, intially it was implemented for subcontracting only. 

Solution:- remove subcontracting = yes condition in validation it will run in all cases where transfer to code = UCWS-VL


@gsudarsan3k  please make the changes in night. already confirmed with venkat, after deployment will get final confirmation for ticket closure.

**Comment by gsudarsan3k** [comment] 2024-12-03 10:10
Hi @Tushargupta3K,

subcontracting = yes condition is removed and code update will deploy the code in PROD today night.

**Comment by Prakash3K** [comment] 2024-12-10 09:46
Client confirmed to close this ticket 


CC: @audhi3k @TabrejAlam3K

**Comment by TabrejAlam3K** [comment] 2024-12-10 09:57
Hi @Tushargupta3K why the effort not updated here.

CC : @audhi3k

**Comment by Prakash3K** [comment] 2024-12-10 10:10
Hi @TabrejAlam3K sir effort hours has been updated now

**Closed as completed by Prakash3K** 2024-12-10 10:10 UTC
