### ISSUE TITLE
The Loan Account Number, Customer Code and Branch Code will be interlinked where if the Loan Account Number or Customer Code is entered then the Customer Code or Loan Account Number and Branch would be auto populated

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#885] opened 2023-10-12 05:24 UTC

**Comment by TabrejAlam3K** [comment] 2023-10-17 02:57
Requirement - While selecting the Loan Dimensio on Journal Voucher Customer Dimension should auto come.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-10-23 06:37
Vridhi Team is not available today we will connect on Wednedsay 25-10-2023

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-10-26 03:36
Discussion Done with the client, For this we can manage the additional Table LMS Records where we can mange the few fields called Customer No.,Branch Code,Loan Acc No.,F Dime 1 and F Dime 2.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-10-27 03:53
Approval mail send to the Client.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-11-02 06:19
Hi Mr. @Mahesh3ktech - This is approved please start working on it.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-11-02 10:13
Hi Mr. @Mahesh3ktech - Ad discussed let me know if required any discussion on this? Please complete it and let me know for UAT.

CC : @audhi3k

**Comment by Mahesh3ktech** [comment] 2023-11-06 11:25
hi @TabrejAlam3K - changes has been done kindly check and update.

CC:@audhi3k @3ktech @gsudarsan3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-11-07 03:33
Hi Mr. @Mahesh3ktech - I have tested the scenario and found it is not working as per our expectation. Can we connect to fix it.

Tested Document
LOAN_REPORT_10262023_112720.csv@ 26/10/2023 13:01

CC : @audhi3k @Shasthara

**Comment by Mahesh3ktech** [comment] 2023-11-07 03:56
hi @TabrejAlam3K - we need to place new file to check this scenario. while inserting data to staging table, data will insert to the new table as well.

CC: @audhi3k @3ktech @gsudarsan3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-11-07 05:42
hi @Mahesh3ktech  - I have asked client to plece one file for testing purpose, let's wait till placing the file by the Client.

Request Mail send for Placing the file in the LMS Folder.

CC: @audhi3k @3ktech @gsudarsan3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-11-09 04:13
It is pending due to file not yet pleaced by the Client side.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-11-22 12:32
It is pending at the client end due to file not yet placed for their internal testing. Once they will confirm we will move the changes into the production.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-11-30 15:21
UAT Completed with the Client, One final round of testing they want to do based on that we will close this ticket tomorrow.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-12-05 05:24
Hi Mr. @Mahesh3ktech - Deploy the changes into the Production. Client confirmed for Deployment and Closure.

Mr. @Prakash3K - You can close this ticket from the support portal **Total Time Effort = 10 Hrs**

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-12-05 05:48
I am closing thic ticket from the git as confirmed by the Client.

CC : @audhi3k @Shasthara @Mahesh3ktech

**Closed as completed by TabrejAlam3K** 2023-12-05 05:48 UTC
Labels: enhancement
