### ISSUE TITLE
RTBs & CRTBs which are already posted in BC365 needs to be triggered to Snowfig LCMS. I can share the list of such RTBs and CRTBs with.

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#448] opened 2023-05-25 04:53 UTC

**Comment by TabrejAlam3K** [comment] 2023-05-26 09:59
Hi Mr. Kartik D @3ktech - Please see the RTB list which are still in **In Billing Process**, Please suggest how we can resolved it.

1. RTB list which are still in **In Billing Process**
2. **LCMS Response Queue** list which are in **In Billing Process**

[RTB-IBP-26-05-2023.xlsx](https://github.com/3ktech/General/files/11573962/RTB-IBP-26-05-2023.xlsx)
[LCMS Response Queue (5).xlsx](https://github.com/3ktech/General/files/11573961/LCMS.Response.Queue.5.xlsx)

CC : @audhi3k @Shasthara @narayana3kt

**Comment by TabrejAlam3K** [comment] 2023-05-29 03:57
Hi Mr. Kartik D @3ktech - Please suggest the solution how we can closed the pending items.

CC : @audhi3k @narayana3kt

**Comment by TabrejAlam3K** [comment] 2023-05-31 04:27
CRTB Part is Completed- Client Confirmed


![Image](https://github.com/3ktech/General/assets/116171982/2df5f6d1-0e6a-41e3-96b5-4ce15b9fe5ac)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-05-31 04:32
For RTB Issues we have analyze tow things below

1. File path is coming wrongly on Azure Portal.
2. Missing Invoice Doc on the azure portal (Pdf copy is not updating automatically) - Need to analyze why it is happening.

**Comment by TabrejAlam3K** [comment] 2023-05-31 04:53
Hi Mr. Kartik D @3ktech - I need you support on this please help me out.

**Comment by TabrejAlam3K** [comment] 2023-06-02 03:53
I am doing testing with the Client.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-06-05 03:34
This point is completed - Still waiting for Confirmation from the client side.

**Comment by TabrejAlam3K** [comment] 2023-06-12 05:00
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k

**Closed as completed by TabrejAlam3K** 2023-06-12 05:00 UTC
