### ISSUE TITLE
Bank Reconciliation Statement: The search option has not been enabled.

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#321] opened 2023-04-26 04:44 UTC

**Comment by TabrejAlam3K** [comment] 2023-04-26 05:13
Clients Comments

Bank Reconciliation Statement: The search option has not been enabled. In addition, in Navision 2016, we were having “Search Option” using Keywords instead of the full name/cheque number in the filter. But, in Navision BC, everywhere we need to provide the full value to reach to that value. The keyword “Search” has not been enabled. Please configure Navision BC for the Search option. Any payment received from clients, the same is getting reflected in Bank Ledger, Customer Ledger, Bank Reconciliation statement. Presently, cheque No. the field is not reflecting the values. Thus, we are unable to get the value of the cheque number. Please ensure the cheque number should be enabled with 30 characters in all the 3 places. Please do the needful.

**Comment by TabrejAlam3K** [comment] 2023-04-26 08:54
@sandhya3k - Please add and enable custom **Cheque No. 2** field in below page.

1. Bank Acc. Reconciliation Lines (380, ListPart) - Add and Enable the Field
2. Apply Bank Acc. Ledger Entries (381, ListPart) - Enable the Field

**Comment by sandhya3k** [comment] 2023-04-26 09:24
@TabrejAlam3K 

 i have enabled the cheque no.2 field please test in UAT environment.

**Comment by TabrejAlam3K** [comment] 2023-04-26 13:11
@sandhya3k I have tested it in the UAT Environment now working fine, Can you please move this in to the Production.

**Comment by TabrejAlam3K** [comment] 2023-04-27 03:40
Cheque No. field is enabled on Bank Ledger, Customer Ledger, Bank Reconciliation statement.

**Comment by TabrejAlam3K** [comment] 2023-04-27 05:38
Keyword behavior is same like nav16.

**Comment by TabrejAlam3K** [comment] 2023-05-19 03:45
This is working fine user need to remove the generated line and make suggest line again.

Ms. @sandhya3k - We need to remove the Check No. field which are having less then 30 Characters.

**Comment by TabrejAlam3K** [comment] 2023-05-26 08:57
Hi Ms. @sandhya3k - Base Check No. field is now removed in UAT Environment. Please move this into the production environment.

**Comment by TabrejAlam3K** [comment] 2023-05-29 04:00
Hi Ms. @sandhya3k - Have you deployed the changes into the production.

CC : @audhi3k @narayana3kt

**Comment by TabrejAlam3K** [comment] 2023-06-12 05:00
As of now we are going to close this issue because client not responded on since long time, We are assuming the issue is working fine.

CC : @audhi3k

**Closed as completed by TabrejAlam3K** 2023-06-12 05:00 UTC
