### ISSUE TITLE
Enable an API  for snowfig to get the status from BC-CAS-01457-K8P7M0

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#578] opened 2023-07-18 05:20 UTC
Approval of the Tickets

![Image](https://github.com/3ktech/General/assets/116171982/ab631ad6-9929-43af-9325-d4c40f1d4659)

**Comment by 3ktech** [comment] 2023-07-18 05:26
hi @Mahesh3ktech , you will have to create an api using flow. let me know when you want to discuss this.
@Shasthara @audhi3k

**Comment by sandhya3k** [comment] 2023-07-20 10:51
@TabrejAlam3K 

We need the approval to do this task.

**Comment by niranjand22** [comment] 2023-07-21 04:50
@TabrejAlam3K  Please coordinate with @sandhya3k

**Comment by TabrejAlam3K** [comment] 2023-07-21 05:52
Hi Ms. @sandhya3k - As per our discussion technical need the approval on this from the client side. 

Mr. @3ktech Kartik D - How much time you have required for this.

Mr. @Shasthara - Once effort receive by Kartik D, Can you check with the client for approval.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-07-24 04:01
Hi Ms. @sandhya3k - Have you not updated how much time you have required for this task.

CC : @audhi3k @3ktech

**Comment by sandhya3k** [comment] 2023-07-24 11:06
5 days

**Comment by TabrejAlam3K** [comment] 2023-07-24 11:28
Hi Ms. @sandhya3k - We will discussed why you have required 5 days for this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-07-27 08:34
Mr. @Shasthara - Please get the approval from the client for this

Technical effort 5Days + Functional Effort 3 Day = Total 8 Days

**8 Days you need to get the approval from the client.**

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-07-31 03:40
Approval Mail sent to the Client.

![Image](https://github.com/3ktech/General/assets/116171982/7ba84020-394e-42d0-8c47-54dbbd0cc75b)

**Comment by TabrejAlam3K** [comment] 2023-08-30 10:41
Hi Mr. @3ktech - Approval Received from the Client side, Please take this task in your pipeline.

![Image](https://github.com/3ktech/General/assets/116171982/1cacace0-f505-472a-8c1b-5f5b35e40f0f)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-09-12 08:35
Hi Mr. @rohit3k & Mr. @Mahesh3ktech - What is the Status of the Ticket

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment] 2023-09-14 02:59
Mr. @TabrejAlam3K - I will do the UAT with the Client (Mr. Somendra) from today based on Somendra availability.

**Comment by TabrejAlam3K** [comment] 2023-09-29 03:51
Waiting for response from the Mr. @3ktech end, He will provide the solution for this to the client (Mr. Somendra)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-10-03 08:10
Hi Mr. @rohit3k and Ms. @sandhya3k - As discussed please deploy the changes into the Production after Office Hours today on priority basis.

CC : @audhi3k @Shasthara @3ktech

**Comment by TabrejAlam3K** [comment] 2023-10-06 04:04
Hi Mr. @Shasthara Can we close this ticket and create the new ticket as per the new time effort?

@rohit3k - Deployment is done into the Production?

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-10-09 03:58
Today I will do the final round of UAT with the client(Mr. Somendra) and update the status.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-10-25 04:09
As per the last session on Monday 2023, Client confirmed for deployment in the Production. After Deployment We will close this ticket.

@audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-10-26 05:21
Hi Mr. @Shasthara - As discussed we will close this ticket today after the Daily Standup Call.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-10-26 05:34
Hi Mr. @Jayanth3KT and Mr. @Prakash3K - This ticket is completed please mark Cust Confirmation in the Support Portal so that mail will be triggred for the Client.

CC : @audhi3k @Shasthara

**Comment by Prakash3K** [comment] 2023-10-26 05:41
@TabrejAlam3K 

![Image](https://github.com/3ktech/General/assets/140147250/506d09c1-50f6-4752-bbcb-164314e5913a)

CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2023-11-08 11:09
Hi Mr. @Shasthara - Can we close this ticket?

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2023-11-10 10:16
Hi Mr. @Shasthara - I am closing this tikcet because testing is completed with all the scenario and it has tested by the Client in the Production as well.

Mr. @Jayanth3KT - You can close this ticket from the Support portal with **effort hours - 87 Hours** (66+18+3)

CC : @audhi3k

**Closed as completed by TabrejAlam3K** 2023-11-10 10:16 UTC
Labels: enhancement
