### ISSUE TITLE
Update of all type of historical data which is not in sync between BC365 and Snowfig

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#1176] opened 2024-01-24 04:23 UTC

**Comment by TabrejAlam3K** [comment] 2024-02-14 09:32
We have done the UAT with the client user Mr. Dipesh and he confirm for deployment.

![Image](https://github.com/3ktech/General/assets/116171982/22640825-ff37-4db9-99a6-ce9e701b6b51)

CC : @audhi3k @Shasthara @rohit3k @3ktech

**Comment by TabrejAlam3K** [comment] 2024-02-16 12:17
Hi Mr. @Prakash3K - We can close this ticket form the Git, You can connect with Mr. @Shasthara and close the ticket from the Support portal.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2024-02-21 03:13
Hi Mr. @rohit3k - As per our discussion and showcase yesterday, Please provide your feedback on Credit Note which is coming In Cancellation Process.

[Historical Data Not Updated 20-02-2024.xlsx](https://github.com/3ktech/General/files/14353566/Historical.Data.Not.Updated.20-02-2024.xlsx)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2024-02-22 08:44
We have already shared our comment to the Client on each points.
1.	Tabrej would check with respect to old RTB, CRTB and write-off records which are still appearing in Snowfig as in Process but has already been posted in BC365, whether the respective records are getting pushed to SB queue or not. 
Comments – We are pushing all the records to SB from the 16th of Feb 2024. For rest of records, we need to push it manually.

**22 Feb 2024** – Mr. Dipesh observed from 16th of Feb there are no entries pending for Snowfig updates, before 16th Feb we found few records, we need to push it manually.

2.	It was also identified that there is a write-off request with RTB number 0000152357 which has been pushed to BC365 but accounts team is not able to access the write-off record in BC365. As checked by Tabrej in logs that the request has been received in BC.
Comments – We are not receiving the Document No. against the WriteOff Request. 

**22 Feb 2024** – Mr. Dipesh Confirmed Snowfig Changes was not deployed on Production, that was the reason WriteOff request reached at BC, but records not get created in “Gen. Journal Lines”.

3.	It was identified that there is a payment received from client against the RTB number [0000881403](https://lcms.snowfig.com/lcmsadmincasefee/newrtb/204665/change/?_changelist_filters=q%3D5048430), but Snowfig system is yet not updated, since the RTB was created in October, so after status API scheduled run the correct status must have been updated, but it is still the same.
Comments – Doc URL is missing on Azure Portal

**22 Feb 2024** – Doc is not yet uploaded over the Azure Portal, It is the reason status does not go back to LCMS.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2024-02-22 08:45
We have already shared our comment to the Client on each points.
1.	Tabrej would check with respect to old RTB, CRTB and write-off records which are still appearing in Snowfig as in Process but has already been posted in BC365, whether the respective records are getting pushed to SB queue or not. 
Comments – We are pushing all the records to SB from the 16th of Feb 2024. For rest of records, we need to push it manually.

**22 Feb 2024** – Mr. Dipesh observed from 16th of Feb there are no entries pending for Snowfig updates, before 16th Feb we found few records, we need to push it manually.

2.	It was also identified that there is a write-off request with RTB number 0000152357 which has been pushed to BC365 but accounts team is not able to access the write-off record in BC365. As checked by Tabrej in logs that the request has been received in BC.
Comments – We are not receiving the Document No. against the WriteOff Request. 

**22 Feb 2024** – Mr. Dipesh Confirmed Snowfig Changes was not deployed on Production, that was the reason WriteOff request reached at BC, but records not get created in “Gen. Journal Lines”.

3.	It was identified that there is a payment received from client against the RTB number [0000881403](https://lcms.snowfig.com/lcmsadmincasefee/newrtb/204665/change/?_changelist_filters=q%3D5048430), but Snowfig system is yet not updated, since the RTB was created in October, so after status API scheduled run the correct status must have been updated, but it is still the same.
Comments – Doc URL is missing on Azure Portal

**22 Feb 2024** – Doc is not yet uploaded over the Azure Portal, It is the reason status does not go back to LCMS.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2024-03-11 03:20
Hi Mr. @rohit3k - whether the RTB rejection issues have been resolved. We need to close this ticket by today before lunch.

CC : @audhi3k @Shasthara

**Comment by rohit3k** [comment] 2024-03-11 04:36
Hi Mr. @TabrejAlam3K  as i have inform you in last conversation that, the button which we have created will work for those Rejected RTB for which we are not having Comment Line entry. if it is working for same kind of scenario that please confirm the Date time for deployment in Production. 

cc: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2024-03-11 04:52
@rohit3k - We have no such scenario available in the Staging Environment.
Share the comment line table name, let me try to replicate the scenario
CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2024-03-11 05:50
Hi Mr. @rohit3k - I have modified the below, Still facing the same error. Please cross check and let us know.
1. Sales header as Cancelled false
2. The comment line removed the comments.

![Image](https://github.com/3ktech/General/assets/116171982/1b4ec663-811e-46ae-ab13-2b80b81868ad)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment] 2024-03-14 10:55
Hi @Prakash3K - Close this ticket from the support portal.

![Image](https://github.com/3ktech/General/assets/116171982/9085196b-6bfd-41ca-a840-0cdc00059c16)

Effort hours - Please check with Mr. @Shasthara 

CC : @audhi3k

**Comment by TabrejAlam3K** [comment] 2024-03-14 11:08
Closing as Completed

![Image](https://github.com/3ktech/General/assets/116171982/710e56e2-914d-4d2e-99a6-40547cdd2b93)

**Closed as completed by TabrejAlam3K** 2024-03-14 11:08 UTC
